### PR TITLE
dev: make a run.sh script to test locally

### PR DESCRIPTION
**Pull request by abhiramtilakiiit**
make a convinient `run.sh` script which similar to the web-nss and other repos, to easily run and test locally.

### CODE REVIEW

**Comment by bhavberi** [comment]
Do we really need a run.sh file with a single command?
@Dileepadari

**Comment by Dileepadari** [comment]
No it's not only one command, you should make npm install in some repos and also setup envs in some.

**Comment by bhavberi** [comment]
Now, you don't need to do anything such, docker files handle that by themselves.
Thus, for running you need to clone with submodules, and directly call `docker compose up --build`

**Comment by Dileepadari** [comment]
deleted run.sh and updated the readme

**Comment by bhavberi** [comment]
Directly updated the README, rather than 3 commits and all.... :)

**Pull request closed without merging**
